### ISSUE TITLE
Advanced grid views

### ISSUE THREAD

**Issue by constantinpape** [mobie/mobie.github.io#58]
I have started to work on the Covid-IF project, https://github.com/mobie/covid-if-project and added the image data for one plate now. This project uses "ome.zarr" as file format (i.e. without additional xmls); we still need to work on opening this in MoBIE (I will work on this with @KateMoreva).

The next step is to add the grid views to create the plate layout, and I want to clarify a few things before starting to work on this.

**Nested grid views:**
To create the well - plate layout, we need to nest the grid views like this (simplified):
```json
"nuclei": {
  "sourceTransforms": [
    {"grid": {"name": "wellA", "sources": ["nucleiA1", "nucleiA2"]}},
    {"grid": {"name": "wellB", "sources": ["nucleiB1", "nucleiB2"]}},
    {"grid": {"name": "plate", "sources": ["wellA", "wellB"]}}
  ]
}
```
I think we discussed this already, @tischi, but I want to double check that this is how we intent to use the grid trafo for the plate layout.

**Reference other views:**
The grid views will be very long in the json, but we may want to specify a view that shows multiple channels, e.g. nuclei, serum and marker.
For this it would be very helpful to have "meta" views (or composite views, combined views, ...) that just list other views that should all be loaded.
Something like this:
```yaml
"plate-view": {  # this view loads the 3 views specified in the view list (which have to be valid names of views)
  "viewList": ["nuclei", "serum", "marker"]
}
```
@tischi, @K-Meech do you think we could add something like this to the spec and support it in MoBIE Fiji?
